# Site settings
title: Samson's Coding Journey and Discoveries
header-img: img/home-bg.png
email: samson.yuwono@gmail.com
copyright_name: samsonyuwono
description: > # this means to ignore newlines until "baseurl:"
  My Journey to becoming a full-stack web developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: EssWhy91
github_username:  samsonyuwono
learn_profile: samsonyuwono
email_username: samson.yuwono@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
